name: Normalize

on:
  push:
    paths:
      - 'composer.json'

concurrency:
  group: normalize-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  normalize:
    runs-on: ubuntu-latest

    name: Normalize composer.json

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Run normalize
        run: |
          composer global require ergebnis/composer-normalize
          composer normalize

      - name: Auto Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'lint: normalize composer.json'
